# Optimization
tune_config:
      #intermediate_dim: tune.choice([5, 10, 20])
      epochs: tune.choice([200])
      lr: tune.choice([0.0009, 0.0003, 0.001])
      batch_size: tune.choice([500])
      seq_in_length: tune.choice([100])
      dilation: tune.choice([1])
      filter_num: tune.choice([64, 128])
      n_layers: tune.choice([1, 2])
      lr_patience: tune.choice([5])
      kernel_size: tune.choice([3, 5, 7, 9])
      pool: tune.choice(['True', 'False']) #if false >>> stride = 2
      activation: tune.choice(['Elu', 'Relu'])  #Only the first capital letter

# Dataset
dataset:
  name: 'sentinel'
  sequential: False
  sample_rate: "4s"
  scaled: True
  clean: True
  shuffle: False #shuffle applied on the row of dataset
  feats: 'all'
  columns: ['RW1_motcurr', 'RW2_motcurr', 'RW3_motcurr', 'RW4_motcurr',
             'RW1_therm', 'RW2_therm', 'RW3_therm', 'RW4_therm',
            'RW1_speed', 'RW2_speed', 'RW3_speed', 'RW4_speed',
            'RW1_cmd_volt', 'RW2_cmd_volt', 'RW3_cmd_volt', 'RW4_cmd_volt']
  #columns: ['RW1_motcurr','RW1_therm',
  #          'RW1_speed', 'RW1_cmd_volt']
  dataset_subset: 1000000
  columns_subset: 0
  target: None
  predict: False
  forecast_all: False
  train_val_split: 0.8

# Model
model:
  name: 'conv_ae1D'

resources:
  gpu_trial: 1
  cpu_trial: 12

opt:
  fine_tuning: False
  tune_report: 'val_loss'
  k_fold_cv: 0
  metrics: ['train_loss', 'val_loss']
  order_by: 'val_loss'
  num_workers: 12

